### PR TITLE
feat: Add the possibility to reload a portalConfig programmatically - EXO-61993 - meeds-io/meeds#606

### PR DESCRIPTION
**Pull request by rdenarie**
This feature allow to reload a portalConfig from configuration. Parameters to find the correct portalConfig are
- ownerType
- predefinedOwner
- location Parameters to configure how to reimport are
- importMode
- overrideMode

### CODE REVIEW

**Review by ahamdi — APPROVED** [review]

**Review by ahamdi — CHANGES_REQUESTED** [review]
Could you add a Unit test for this new function ?

**Comment by rdenarie** [comment]
@ahamdi unit test added

**Comment by ahamdi** [comment]
> @ahamdi unit test added

It seems that the file change didn't appear yet in the PR

**Comment by rdenarie** [comment]
> > @ahamdi unit test added
> 
> It seems that the file change didn't appear yet in the PR

Sorry, forgot to push ...

**Comment by rdenarie** [comment]
@ahamdi build is now ok and unit test added. Thanks

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
