### PR TITLE
TASK-59005:  Merge all 3 US's of OIDC refectoring

### PR DESCRIPTION
**Pull request by hchaabene**
Task-58297 :
https://github.com/Meeds-io/gatein-portal/commit/914fe307886faedfba0f4e06f5a52a8ff156ed21
Task-58776 :
https://github.com/Meeds-io/gatein-portal/commit/bdf8536bf921d48666cdeaf890cfcfa95f788315
Task-58777 : 
https://github.com/Meeds-io/gatein-portal/commit/3b7bc824c8444e24b2b602ac9cd0080b758ff8ea

### CODE REVIEW

**Comment by ahamdi** [comment]
@hchaabene Could you check the build failure ? it is looking for javax.json package , didn't we remove that dependency ?

**Review by ahamdi — APPROVED** [review]
Please take care to do a rebase and do not squash the commits , thanks

**Comment by rdenarie** [comment]
Please wait for my last test with adfs server before merging. Thanks

**Review by rdenarie — APPROVED** [review]
It is ok for me.
We had a problem with the adfs server so I was unable to make all the tests.

**Pull request merged**
